name: job2
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
jobs:
  try-download:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: check before download
        run: |
          echo "Hello, world!"
          pwd
          ls
      - uses: actions/download-artifact@v4
        with:
          name: foo-artifact
      - name: check after download
        run: |
          echo "Hello, world!"
          ls -lR
          tar -xjf foo-artifact/foo.tar.bz2
          ls -lR
