name: Manual workflow
on:
  workflow_dispatch:
jobs:
  echo-hello:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Echo Hello
        run: |
          echo "Hello, world!"
          pwd
          uname -a
          free -m
          cat /etc/lsb-release
          ls -la
          echo "hello" > foo
          mkdir bar
          echo "world" > bar/foo
          tar -cjf foo.tar.bz2 foo bar
      - uses: actions/upload-artifact@v4
        with:
          name: foo-artifact
          path: foo.tar.bz2
